# fly.toml app configuration file generated for dedent-app on 2026-05-11T22:00:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dedent-app'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  PHX_HOST = 'dedent-app.fly.dev'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
